"""
Create a tropical cyclone hazard file from Gori et al. (2025) wind field data.

This script loads wind field .mat files and corresponding storm track information 
from **Gori et al. (2025)** in a CLIMADA-compatible workflow. It builds a 
`tropical_cyclone` `Hazard` object and saves it as an HDF5 file that can be used 
directly in downstream impact, recovery, and risk analyses.

Inputs:
- `mat_dir`: Directory containing individual wind field .mat files generated by Gori et al. (2025).
- `track_mat_path`: Path to the .mat file with tropical cyclone track information.
- `resolution_deg`: Target grid resolution (in degrees).
- `pad_deg`: Geographic padding around the wind field domain (in degrees).

Output:
- HDF5 hazard file written to:
  `/home/groups/bakerjw/smeiler/climada_data/data/hazard/tropical_cyclone/gori/tc_ncep_reanal.hdf5`

Usage:
    python scripts/build_tc_hazard.py
"""

from pathlib import Path
from modules.hazard_funcs import load_tc_hazard_from_wind_mats

# base directory where hazard input files live
haz_dir = Path("/home/groups/bakerjw/smeiler/climada_data/data/hazard")

# input files
mat_dir = haz_dir / "tropical_cyclone" / "gori" / "ncep_reanal"
track_mat_path = haz_dir / "tropical_cyclone" / "gori" / "UScoast6_AL_ncep_reanal_roEst1rmEst1_trk100.mat"

# build hazard object
haz = load_tc_hazard_from_wind_mats(
    mat_dir=mat_dir,
    track_mat_path=track_mat_path,
    resolution_deg=0.1,
    pad_deg=1.0,
)

# write to HDF5
out_path = haz_dir / "tropical_cyclone" / "gori" / "tc_ncep_reanal.hdf5"
haz.write_hdf5(out_path)
