"""
Create a tropical cyclone hazard file from Gori et al. (2025) wind field data.

This script loads wind field .mat files and corresponding storm track information 
from **Gori et al. (2025)** in a CLIMADA-compatible workflow. It builds a 
`tropical_cyclone` `Hazard` object and saves it as an HDF5 file that can be used 
directly in downstream impact, recovery, and risk analyses.

Builds a single hazard from ALL available .mat files in the MAT directory (not chunked).
Skips missing files (preserves event naming from filenames) and assigns per-event frequencies
using TOTAL_STORMS = 5018 to match the chunked approach.

Inputs:
- `mat_dir`: Directory containing individual wind field .mat files generated by Gori et al. (2025).
- `track_mat_path`: Path to the .mat file with tropical cyclone track information.
- `resolution_deg`: Target grid resolution (in degrees).
- `pad_deg`: Geographic padding around the wind field domain (in degrees).

Output:
- HDF5 hazard file written to:
  `/home/groups/bakerjw/smeiler/climada_data/data/hazard/tropical_cyclone/gori/tc_ncep_reanal.hdf5`

Usage:
    python scripts/make_haz_gori.py
"""

from pathlib import Path
from tempfile import TemporaryDirectory
import os
import re
import numpy as np

from modules.hazard_utils import load_tc_hazard_from_wind_mats, _read_catalog_freq

# base directory where hazard input files live
HAZ_DIR = Path("/home/groups/bakerjw/smeiler/climada_data/data/hazard")

# input files
MAT_DIR = HAZ_DIR / "tropical_cyclone" / "gori" / "ncep_reanal"
TRACK_MAT_PATH = HAZ_DIR / "tropical_cyclone" / "gori" / "UScoast6_AL_ncep_reanal_roEst1rmEst1_trk100.mat"

TOTAL_STORMS = 5018  # hard-coded total across the whole catalog (to match chunked approach)
OUT_DIR = HAZ_DIR / "tropical_cyclone" / "gori"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Use $SCRATCH if available for temp symlink dir (faster I/O)
SCRATCH = Path(os.environ.get("SCRATCH", "/tmp"))

print("[HRP] Building single hazard from ALL available .mat files in MAT_DIR")
print(f"[HRP] MAT_DIR: {MAT_DIR}")

# Discover all .mat files (skipping missing ones, preserving numeric ordering)
# Event naming comes from filenames; we preserve gaps in numbering
all_files = sorted(MAT_DIR.glob("*.mat"))
if not all_files:
    raise FileNotFoundError(f"No .mat files in {MAT_DIR}")

print(f"[HRP] Found {len(all_files)} .mat files total")

# Create temp dir and symlink all available files
with TemporaryDirectory(dir=SCRATCH) as tmp:
    tmp_dir = Path(tmp)
    for fp in all_files:
        (tmp_dir / fp.name).symlink_to(fp)
    
    print(f"[HRP] Symlinked {len(all_files)} files into {tmp_dir}")
    
    # build hazard object from all files in one pass (single global centroid grid)
    print("[HRP] Building hazard (this may take significant memory)...")
    haz = load_tc_hazard_from_wind_mats(
        mat_dir=tmp_dir,
        track_mat_path=TRACK_MAT_PATH,
        resolution_deg=0.1,
        pad_deg=1.0,
    )

print(f"[HRP] Hazard built: {haz.size} events, {haz.centroids.size} centroids")

# ---- set per-event frequency = freq_scalar / TOTAL_STORMS (hard-coded total) ----
freq_scalar = _read_catalog_freq(TRACK_MAT_PATH)  # events/year scalar
per_event = float(freq_scalar) / float(TOTAL_STORMS)
haz.frequency = np.full(haz.event_id.size, per_event, dtype=float)
try:
    haz.frequency_unit = "1/year"
except AttributeError:
    pass

# tag
try:
    haz.tag = "gori_ncep_reanal_all_events"
except Exception:
    pass

# write to HDF5
out_path = OUT_DIR / "tc_ncep_reanal.hdf5"
print(f"[HRP] Writing HDF5 to {out_path}")
haz.write_hdf5(out_path)
print("[HRP] Done.")
